import { bindElementsById } from "../ui/dom.js";

export const REQUIRED_ELEMENT_IDS = [
  "dayLabel",
  "encounterOverlay",
  "phaseLabel",
  "runStateLabel",
  "mapPartySelect",
  "overlandMap",
  "locationDetail",
  "operationRows",
  "poiRows",
  "tavernStatus",
  "tavernResourceLine",
  "upgradeTavernBtn",
  "visitorRows",
  "tavernVisitorDetailBox",
  "jobRows",
  "populationResourceRows",
  "settlementWageControls",
  "workshopStatus",
  "workshopSlots",
  "workshopResearch",
  "workshopUpgradeGraph",
  "rosterRows",
  "partyRows",
  "focusedCharacterBox",
  "partyStatus",
  "toggleRosterViewBtn",
  "partySelect",
  "dungeonSelect",
  "strategySelect",
  "stopNodeSelect",
  "repeatSelect",
  "nodeMap",
  "dungeonNodeInfo",
  "estimateBox",
  "replayStatus",
  "replayPartyActors",
  "replayEnemyActors",
  "replayActionIcon",
  "replayEventText",
  "replayEventRows",
  "replayTimelineSlider",
  "templeStatus",
  "templeStoneButtons",
  "templeMatrix",
  "templeBuffRows",
  "shardInventoryRows",
  "shardDetailBox",
  "logRows",
  "blueprintRows"
];

export function bindAppElements(root = document) {
  return bindElementsById(REQUIRED_ELEMENT_IDS, root);
}
